### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by xdamman**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/tld.js ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by remusao** [comment]
Hey,

I have no influence on this PR myself, but I just wanted to comment that, if this is merged, the dependencies of this package (currently only `punycode` => 60 KB) will go from one to (by transitivity) 43 (~25 MB). I like the idea of having a minimum set of dependencies to `tld.js`, adding `opencollective` to it seems a bit overkill IMO.

Also, I don't know if anyone asked for it (I would guess not), or if this is desirable at all for the project, but I had no idea what opencollective was before this PR (seems to be just starting?). Maybe you could explain a bit the concept in the PR.

Cheers,

**Comment by xdamman** [comment]
@remusao Hi Remi. I understand the concern. That's why it's optional to add that dependency. Feel free to remove it. Open Collective is a new concept but it's been around almost 2 years now. There are plenty of open source projects on the platform: https://opencollective.com/opensource and you can read more about the concept here: https://medium.com/open-collective/a-new-way-to-fund-open-source-projects-91a51b1b7aac#.ky05pse2h

**Comment by oncletom** [comment]
Actually I did the request on OpenCollective, like today, as I was willing to test and see how it works in the wild.

It starts to have a few [dependents on npm](https://www.npmjs.com/browse/depended/tldjs) (47) so if there a few services/people who do business thanks to it, I would be happy to offer them the ability to top up. Even if in the end we have nothing to pay for, I'd happily give the money to Mozilla or the PublicSuffix project to pay for their infrastructure etc.

I agree the extra dependency is not necessary at all, and I'd rather not make end users to pay the price of it.

**Comment by oncletom** [comment]
@remusao also, I have to say, I understood OpenCollective just today after browsing https://opencollective.com/learn-more.

At first, I thought it was just a way to collect money but then I understood it was a fair and cooperative way of making decisions with the project budget without having to create a formal and legal structure.

**Comment by remusao** [comment]
@xdamman My apologies for a possibly not very welcoming tone in my first message. I should have waited for @oncletom to answer before commenting.

Thank you for pointing to resources to better understand your project. That seems like a nice idea!

Could we then remove the extra dependency and revert the change on the postinstall hook? The rest looks good to me.

**Comment by xdamman** [comment]
No worries ;-)

Yes of course. Feel free to edit the PR to remove that. It's a generic template semi automatically generated that can be adapted by the project.

**Comment by oncletom** [comment]
Let's go ahead.

It might be of the interest of cdnjs/cdnjs#8943 :-)

**Pull request merged**
