### PR TITLE
Update rules.json

### LINKED ISSUE #69: Remove .an domain
It has been discontinued as of 31 July 2015 https://en.wikipedia.org/wiki/.an

### PR DESCRIPTION
**Pull request by Kureev**
Fixes #69

### CODE REVIEW

**Comment by Kureev** [comment]
Any news so far?

**Comment by oncletom** [comment]
Hey! It seems all good, although the tests seem to fail for some reason (testling hangs).

**Comment by oncletom** [comment]
And published as `1.6.1` :-)

**Comment by Kureev** [comment]
thanks :heart:

**Comment by felixhageloh** [comment]
Thanks for merging! Not quite sure what happened, but for some reason `an` is still in the rules list. Should I open another issue for this?

**Comment by oncletom** [comment]
@felixhageloh yes please, it will be reflected in the CHANGELOG this way :-) Thanks!

**Pull request merged**
